layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  email: sshagunsodhani@gmail.com
  github: shagunsodhani
  twitter: shagunsodhani
  scholar: ixp-vqMAAAAJ
  # stackoverflow: 1353861
  linkedin: shagunsodhani
  # telegram: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Research
    web_url: https://scholar.google.ca/citations?user=ixp-vqMAAAAJ&hl=en
    image_url: /assets/imgs/logos/scholar.png
    image_width: 64
    image_height: 64

  - name: Projects
    web_url: /projects/
    image_url: /assets/imgs/logos/github.jpg
    image_width: 80
    image_height: 64

  - name: Talks
    web_url: https://shagunsodhani.github.io/talks/
    image_url: /assets/imgs/logos/talk.jpeg  
    image_width: 90
    image_height: 64

  - name: Professional Services
    web_url: /service/
    image_url: /assets/imgs/logos/service.jpg 
    image_width: 64
    image_height: 64

  - name: Teaching/Mentoring
    web_url: /mentoring
    image_url: /assets/imgs/logos/mentor.jpg  
    image_width: 128
    image_height: 64

mentoring:
  - name: AI Mentor
    description: CBC-Radio Canada Hackathon, 2019
    web_url: https://www.agorize.com/en/challenges/cbc-radio-canada-hackathon-2019
    image_url: /assets/imgs/logos/cbc.png
    image_width: 128
    image_height: 64

  - name: Teaching Assistant
    description: Data Mining Techniques, Masters Course, HEC, Montreal, 2019
    web_url: https://www.hec.ca/en/courses/detail/?cours=MATH60600A
    image_url: /assets/imgs/logos/hec.gif
    image_width: 64
    image_height: 64

  - name: Teaching Assistant
    description: Data Mining Techniques, Masters Course, HEC, Montreal, 2018
    web_url: https://www.hec.ca/en/courses/detail/?cours=MATH60600A
    image_url: /assets/imgs/logos/hec.gif
    image_width: 64
    image_height: 64

  - name: Mentor
    description: AI for Social Good Lab, 2018
    web_url: https://www.aiforsocialgood.ca
    image_url: /assets/imgs/logos/ai_for_social_good.jpg
    image_width: 128
    image_height: 64

  - name: Mentor
    description: Educational Program for Employees, Adobe Systems, 2017
    web_url: https://www.adobe.com
    image_url: /assets/imgs/logos/adobe.jpg
    image_width: 64
    image_height: 64

  - name: Teaching Assistant
    description: Data Science and Engineering with Spark XSeries
    web_url: https://www.edx.org/xseries/data-science-engineering-apacher-sparktm
    image_url: /assets/imgs/logos/edx.png
    image_width: 128
    image_height: 64

service:

  organizer:

    - name: Lifelong Learning - A Reinforcement Learning Approach Workshop, RLDM 2019
      description: Organizer
      web_url: https://sites.google.com/view/llarla/home
      # image_url: /assets/imgs/logos/rldm.png
      # image_width: 80
      # image_height: 80

    - name: Workshop on Multi-Task and Lifelong Reinforcement Learning, ICML 2019
      description: Organizer
      web_url: https://sites.google.com/view/mtlrl/
      # image_url: /assets/imgs/logos/mtlrl.png
      # image_width: 80
      # image_height: 80

    - name: Workshop on Deep Learning for Graphs, SDM 2019
      description: Organizer
      web_url: https://sites.google.com/view/graph-representation-workshop/
      # image_url: /assets/imgs/logos/sdm.png
      # image_width: 128
      # image_height: 80

  reviewer:

    - name: International Conference for Learning Representations (ICLR)
      description: Reviewer
      web_url: https://iclr.cc
      # image_url: /assets/imgs/logos/iclr.png
      # image_width: 80
      # image_height: 80

    - name: PyData Conference 2019
      description: Reviewer
      web_url: https://pydata.org/delhi2019/
      # image_url: /assets/imgs/logos/pydata.png
      # image_width: 160
      # image_height: 80

    - name: Montreal AI Symposium (MAIS)
      description: Reviewer
      web_url: https://montrealaisymposium.wordpress.com
      # image_url: /assets/imgs/logos/mais.png
      # image_width: 160
      # image_height: 80

    - name: Learning and Reasoning with Graph-Structured Representations, ICML 2019 Workshop
      description: Program Committee
      web_url: https://graphreason.github.io/index.html
      # image_url: /assets/imgs/logos/graphreason.png
      # image_width: 80
      # image_height: 80

    - name: AI for Social Good, ICML 2019 Workshop
      description: Reviewer
      web_url: https://aiforsocialgood.github.io/icml2019/
      # image_url: /assets/imgs/logos/aisg.png
      # image_width: 128
      # image_height: 80

    - name: Representation Learning on Graphs and Manifolds, ICLR 2019 Workshop
      description: Program Committee
      web_url: https://rlgm.github.io/
      # image_url: /assets/imgs/logos/rlgm.png
      # image_width: 128
      # image_height: 80

    - name: AI for Social Good, NeurIPS 2018 Workshop
      description: Reviewer
      web_url: https://aiforsocialgood.github.io/2018/
      # image_url: /assets/imgs/logos/aisg.png
      # image_width: 128
      # image_height: 80
    